spring.application.name=employee-api

spring.datasource.url=jdbc:h2:mem:employees
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

server.port=${PORT:8080}
